name: Blog
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Cache Gatsby
        uses: actions/cache@v2
        id: blog-gatsby-cache
        with:
          path: |
            websites/www.giuem.com/.cache
            websites/www.giuem.com/public
          key: ${{ runner.os }}-blog-gatsby-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-blog-gatsby-cache-
      - run: pnpm install
      - name: Build Blog
        run: pnpm build --filter www.giuem.com
      - name: Publish
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'websites/www.giuem.com'
