name: CI
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.10
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Setup pnpm Cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-
      - run: pnpm install
      - run: pnpm lint

      - name: Cache Gatsby
        uses: actions/cache@v2
        id: blog-gatsby-cache
        with:
          path: |
            apps/www.giuem.com/.cache
            apps/www.giuem.com/public
          key: gatsby-cache-${{ github.sha }}
          restore-keys: |
            gatsby-cache-

      # - name: Cache Turbo
      #   uses: actions/cache@v2
      #   with:
      #     path: .turbo
      #     key: turbo-cache-${{ github.ref_name }}-${{ github.sha }}
      #     restore-keys:

      - name: Build
        run: pnpm turbo run build --cache-dir=".turbo"
      - name: Publish
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'apps/www.giuem.com'
