name: CI
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.10
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm lint

      - name: Cache Gatsby
        uses: actions/cache@v2
        id: blog-gatsby-cache
        with:
          path: |
            apps/www.giuem.com/.cache
            apps/www.giuem.com/public
          key: gatsby-cache-${{ github.sha }}
          restore-keys: |
            gatsby-cache-

      - name: Build
        run: pnpm turbo run build
      # - name: Publish
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: cloudflare/wrangler-action@1.3.0
      #   with:
      #     apiToken: ${{ secrets.CF_API_TOKEN }}
      #     workingDirectory: 'apps/www.giuem.com'
